apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy  # name of the deployment  created

spec:
  replicas: 4
  template:
    metadata:
      name: pod-deploy # name of the pod
      labels: 
        app: 07Dec # Label of the Pod
    spec:
      containers:
        - name: pod-deploy-container  # name of the container
          image: jenkins/jenkins:lts  # name of the image from dockerhub
          #image: nginx ------ COMMENTED
          volumeMounts:
            - name: jenkinsvol # 
              mountPath: /var/jenkins_home # Container's directory which will be mounted

      volumes: 
        - name: jenkinsvol   # volume name and volumeMounts name must be same.
          hostPath:
            path: /data/jen    # target path of the host volume (Mountpoint)
            type: Directory


  selector:
    matchLabels:
      app: 07Dec  # selector helps the replicaset to find all the matching label pods
